# -*- coding: utf-8 -*-
"""Factorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wjXL7s9gc2XXtbZyJ3p3J7cWgCUaqPgx

Factorial
"""

n = 5
fact = 1
for i in range(1, n + 1):
   fact= fact*i

print(fact)